name: Docs

on: push

jobs:
  convert_via_pandoc:
    name: Generate Docs
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, '[docs]')"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: MeilCli/setup-crystal-action@v4.4.2
        with:
          crystal_version: 0.34.0
          shards_version: 0.10.0
      - name: Run Crystal
        run: |
          export GRANZ_BUILD=TRUE
          shards install
          crystal run ./src/Granz.cr
          mv ./commands.json ./docs/assets/commands.json
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./docs/assets/commands.json ./commands.md
          git commit -m "feat(docs): generate"
          git push "https://GeopJr:${{ secrets.GITHUB_TOKEN }}@github.com/GeopJr/Granz-cr.git" HEAD:main
